using System;

namespace ALOD.Core.Domain.Modules.SpecialCases
{
    [Serializable]
    public class PAL_Data : Entity
    {
        public virtual String AdditionalComments { get; set; }
        public virtual int AFForm422 { get; set; }
        public virtual int? ALC_C { get; set; }
        public virtual int Archive { get; set; }
        public virtual String ArtAndDSN { get; set; }
        public virtual String ASC_Code { get; set; }
        public virtual int Asthma_Gen12 { get; set; }
        public virtual String BaseAssign { get; set; }
        public virtual int CAD_12_1 { get; set; }
        public virtual int Cancer { get; set; }
        public virtual String CompletedBy { get; set; }
        public virtual int CONUS { get; set; }
        public virtual int CONUS_IfCheckedFirst { get; set; }
        public virtual int Coronary { get; set; }
        public virtual DateTime? DateOfBirth { get; set; }
        public virtual DateTime? DateOut { get; set; }
        public virtual DateTime? DateRec { get; set; }
        public virtual DateTime? DateSentToFiche { get; set; }
        public virtual int Dental { get; set; }
        public virtual String Diagnosis { get; set; }
        public virtual int Discharged { get; set; }
        public virtual String DischargeDesc { get; set; }
        public virtual String Disposition { get; set; }
        public virtual int DM { get; set; }
        public virtual int DM_12_2 { get; set; }
        public virtual String DQDiagnosis { get; set; }
        public virtual String DQParaNumber { get; set; }
        public virtual int EENT { get; set; }
        public virtual DateTime? ExpireDate { get; set; }
        public virtual String Fiche { get; set; }
        public virtual String FirstName { get; set; }
        public virtual int GI { get; set; }
        public virtual String HeShe { get; set; }
        public virtual String HeShe_NotCapped { get; set; }
        public virtual String HimHer { get; set; }
        public virtual String HisHer { get; set; }
        public virtual int HIV { get; set; }
        public virtual int HIV_12_3 { get; set; }
        public virtual int HomeStation { get; set; }
        public virtual int IndefiniteWaiver { get; set; }
        public virtual String InputBy { get; set; }
        public virtual int IPEBElectedNo { get; set; }
        public virtual int IPEBElectedYes { get; set; }
        public virtual int IPEBElectionIncluded { get; set; }
        public virtual String LastName { get; set; }
        public virtual int MedicalEvaluationFactSheet { get; set; }
        public virtual int Musculoskeletal { get; set; }
        public virtual int NarrativeSummary { get; set; }
        public virtual int Neuro { get; set; }
        public virtual int NoHome { get; set; }
        public virtual int Other { get; set; }
        public virtual int Psych { get; set; }
        public virtual int Psych_12_4 { get; set; }
        public virtual int Pulmonary { get; set; }
        public virtual int Questionnaire { get; set; }
        public virtual String Rank { get; set; }
        public virtual String Rating { get; set; }
        public virtual int RcdId { get; set; }
        public virtual int ReActivate { get; set; }
        public virtual String ReceivedFrom { get; set; }
        public virtual String Remarks { get; set; }
        public virtual int Renewal { get; set; }
        public virtual int Retired { get; set; }
        public virtual String RetiredDesc { get; set; }
        public virtual String RetToDutyBy { get; set; }
        public virtual int RK { get; set; }
        public virtual int RWOA { get; set; }
        public virtual String RWOA_Reason { get; set; }
        public virtual int Section1 { get; set; }
        public virtual int Section10 { get; set; }
        public virtual int Section10_1 { get; set; }
        public virtual int Section10_2 { get; set; }
        public virtual int Section10_3 { get; set; }
        public virtual int Section11 { get; set; }
        public virtual int Section13 { get; set; }
        public virtual int Section15 { get; set; }
        public virtual int Section16 { get; set; }
        public virtual int Section16_1 { get; set; }
        public virtual int Section16_2 { get; set; }
        public virtual int Section16_2_1 { get; set; }
        public virtual int Section16_3 { get; set; }
        public virtual int Section16_4 { get; set; }
        public virtual int Section16_5 { get; set; }
        public virtual int Section16_5A { get; set; }
        public virtual int Section16_6 { get; set; }
        public virtual int Section16_7 { get; set; }
        public virtual int Section16_7A { get; set; }
        public virtual int Section16_7B { get; set; }
        public virtual int Section18 { get; set; }
        public virtual int Section20 { get; set; }
        public virtual int Section21 { get; set; }
        public virtual int Section21_1 { get; set; }
        public virtual int Section22 { get; set; }
        public virtual int Section3 { get; set; }
        public virtual int Section3_1 { get; set; }
        public virtual int Section4 { get; set; }
        public virtual int Section4_1 { get; set; }
        public virtual int Section4_1_1 { get; set; }
        public virtual int Section4_2 { get; set; }
        public virtual int Section4_3 { get; set; }
        public virtual int Section4_4 { get; set; }
        public virtual int Section4_5 { get; set; }
        public virtual int Section5 { get; set; }
        public virtual int Section6 { get; set; }
        public virtual int Section6_1 { get; set; }
        public virtual int Section7 { get; set; }
        public virtual int Section8 { get; set; }
        public virtual int Section9 { get; set; }
        public virtual int Section9_1 { get; set; }
        public virtual String Sent_To { get; set; }
        public virtual String Signature { get; set; }
        public virtual String SSN { get; set; }
        public virtual int TRWOA { get; set; }
        public virtual String Type { get; set; }
        public virtual int UnitCommanderMemo { get; set; }
        public virtual int WNLR { get; set; }
    }
}