'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Reports
    
    Partial Public Class Secure_Reports_AdhocResults
        
        '''<summary>
        '''pnlErrors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlErrors As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblQueryId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblQueryId As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblQueryTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblQueryTitle As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''bllErrors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bllErrors As Global.System.Web.UI.WebControls.BulletedList
        
        '''<summary>
        '''pnlResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlResults As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''CountLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CountLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ResultsGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ResultsGrid As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
