'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Reports
    
    Partial Public Class Secure_Reports_LodDisposition
        
        '''<summary>
        '''rptTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptTemplate As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_ReportNav
        
        '''<summary>
        '''upnlSigBlock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlSigBlock As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''SigBlock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigBlock As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SignatureBlock
        
        '''<summary>
        '''ErrorLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''memberSelectionUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents memberSelectionUpdatePanel As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''MemberSelectionPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberSelectionPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''ucMemberSelectionGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucMemberSelectionGrid As Global.ALOD.Web.UserControls.MemberSearchResultsGrid
        
        '''<summary>
        '''resultsUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents resultsUpdatePanel As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''imgWait control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgWait As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''ResultsPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ResultsPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''GridViewErrorLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewErrorLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ReportGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportGrid As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''resultsUpdatePanelAnimationExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents resultsUpdatePanelAnimationExtender As Global.AjaxControlToolkit.UpdatePanelAnimationExtender
    End Class
End Namespace
