'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Reports

    Partial Public Class Secure_Reports_LodStatistics

        '''<summary>
        '''rptNav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptNav As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_ReportNav

        '''<summary>
        '''resultsUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents resultsUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''imgWait control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgWait As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''StatGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''detailsUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents detailsUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''DetailDiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DetailDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''DetailsCatLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DetailsCatLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DetailsMonthLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DetailsMonthLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DetailGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DetailGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''resultsUpdatePanelAnimationExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents resultsUpdatePanelAnimationExtender As Global.AjaxControlToolkit.UpdatePanelAnimationExtender

        '''<summary>
        '''detailsUpdatePanelAnimationExtender1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents detailsUpdatePanelAnimationExtender1 As Global.AjaxControlToolkit.UpdatePanelAnimationExtender
    End Class
End Namespace
