'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case

    Partial Public Class Secure_sc_ci_Start

        '''<summary>
        '''InputPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InputPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''upnlMemberLookup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlMemberLookup As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''trRadioButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trRadioButtons As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''rdbSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbSSN As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rdbName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbName As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''trSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSSN As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''SSNTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SSNTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''NotFoundLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NotFoundLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''InvalidSSNLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InvalidSSNLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvalidMemberForSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvalidMemberForSSN As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trSSN2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSSN2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''SSNTextBox2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SSNTextBox2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''InvalidLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InvalidLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''InvalidSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InvalidSSN As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''txtMemberLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMemberFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMemberMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberMiddleName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMemberNotFound control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMemberNotFound As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvalidMemberName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvalidMemberName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvalidMemberForName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvalidMemberForName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LookupButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LookupButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''MemberSelectionPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberSelectionPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ucMemberSelectionGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucMemberSelectionGrid As Global.ALOD.Web.UserControls.MemberSearchResultsGrid

        '''<summary>
        '''MemberDataPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberDataPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''SSNLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SSNLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ChangeSsnButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChangeSsnButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''CompoLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompoLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''upnlMemberData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlMemberData As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''NameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DoBLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DoBLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''GradeCodeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GradeCodeLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''RankLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RankLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UnitNameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitNameLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UnitCodeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitCodeLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UnitIdLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitIdLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CompoSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompoSelect As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlCompo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCompo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rowModuleType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowModuleType As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''moduleLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moduleLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlModule As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rowSimDeploy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowSimDeploy As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''rbYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbYes As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rbNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbNo As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''RadioButtonList1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadioButtonList1 As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''rowMAJCOM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowMAJCOM As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblMAJCOM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMAJCOM As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlMAJCOM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMAJCOM As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''BMTModuleSubType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BMTModuleSubType As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ddlSubModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSubModule As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''PSCDAssociatedCaseType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PSCDAssociatedCaseType As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''AssociatedCaseTypeDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedCaseTypeDropDownList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''AssociatedLODRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedLODRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''AssociatedLODListHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedLODListHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''sectionAssociatedLOD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionAssociatedLOD As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lodRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lodRequired As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''AssociatedLODListLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedLODListLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''AssociatedLODList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedLODList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblAssociatedLODs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAssociatedLODs As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlLODs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLODs As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''AssociatedLODMultiple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedLODMultiple As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblAssociatedLODMultiple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAssociatedLODMultiple As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''MultipleLODs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MultipleLODs As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''AssociatedWWDRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedWWDRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''AssociatedWWDListHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedWWDListHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''sectionAssociatedWWD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionAssociatedWWD As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''AssociatedWWDListLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedWWDListLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''AssociatedWWDList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedWWDList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ddlWWDs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlWWDs As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''AssociatedIRRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedIRRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''AssociatedIRListHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedIRListHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''sectionAssociatedIR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionAssociatedIR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''AssociatedIRListLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedIRListLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''AssociatedIRList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedIRList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ddlIR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIR As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''AssociatedSCRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedSCRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''AssociatedSCListHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedSCListHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''sectionAssociatedSC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionAssociatedSC As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''scRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents scRequired As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''AssociatedSCListLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedSCListLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblAssociatedSCList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAssociatedSCList As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''AssociatedSCList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedSCList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ddlSCs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSCs As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''AssociatedRWRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedRWRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''AssociatedRWListHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedRWListHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''sectionAssociatedRW control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionAssociatedRW As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''AssociatedRWListLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedRWListLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''AssociatedRWList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociatedRWList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ddlRWs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRWs As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''PEPPSubTypeRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PEPPSubTypeRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''PEPPSubTypeListHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PEPPSubTypeListHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''sectionPEPPSubType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionPEPPSubType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''peppSubTypeRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents peppSubTypeRequired As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''PEPPSubTypeListLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PEPPSubTypeListLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PEPPSubTypeList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PEPPSubTypeList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ddlPEPPSubType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPEPPSubType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''CaseTypeRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CaseTypeRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''CaseTypeListHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CaseTypeListHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSectionCaseType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSectionCaseType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''caseTypeRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents caseTypeRequired As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''caseTypeListLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents caseTypeListLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''caseTypeList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents caseTypeList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ddlCaseType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCaseType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''OtherCaseTypeRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OtherCaseTypeRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''txtCaseTypeName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCaseTypeName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubCaseTypeRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubCaseTypeRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''SubCaseTypeListHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubCaseTypeListHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSectionSubCaseType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSectionSubCaseType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''subCaseTypeRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subCaseTypeRequired As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''subCaseTypeListLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subCaseTypeListLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''subCaseTypeList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents subCaseTypeList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ddlSubCaseType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSubCaseType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''OtherSubCaseTypeRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OtherSubCaseTypeRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''txtSubCaseTypeName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubCaseTypeName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''nesRequestEligibleRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nesRequestEligibleRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''nesRequestEligibleHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nesRequestEligibleHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''nesRequestEligible control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nesRequestEligible As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''nesRequestEligibleLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nesRequestEligibleLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblNESRequestEligible control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNESRequestEligible As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''nesRequestEligibleRadioButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nesRequestEligibleRadioButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rdbNESYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbNESYes As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rdbNESNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbNESNo As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''nesRequestEligibieDecisionLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents nesRequestEligibieDecisionLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''sectionAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionAction As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CreateButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CreateButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''SigBlock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigBlock As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SignatureBlock

        '''<summary>
        '''ErrorRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''sectionErrors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionErrors As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ErrorLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''WorkflowRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkflowRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''sectionWorkflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionWorkflow As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlWorkflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlWorkflow As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ValidationErrorsRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationErrorsRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ValidationList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationList As Global.System.Web.UI.WebControls.BulletedList

        '''<summary>
        '''HistoryPanelLOD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryPanelLOD As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''HistoryGridLOD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryGridLOD As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''NoHistoryLODLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NoHistoryLODLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HistoryPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''HistoryGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''NoHistoryLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NoHistoryLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Data_BMTSubTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Data_BMTSubTypes As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''Data_PEPPSubTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Data_PEPPSubTypes As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
