'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.RW
    
    Partial Public Class Secure_sc_rw_MedTech
        
        '''<summary>
        '''pnlMedTechControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMedTechControls As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''txtRenewalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRenewalDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlMedGroups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMedGroups As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblRMU control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRMU As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ddlRMUs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRMUs As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''upnlMedTechICDControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlMedTechICDControl As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''ucICDCodeControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucICDCodeControl As Global.ALOD.Web.UserControls.ICDCodeControl
        
        '''<summary>
        '''upnlMedTech7thCharacterControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlMedTech7thCharacterControl As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''ucICD7thCharacterControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucICD7thCharacterControl As Global.ALOD.Web.UserControls.ICD7thCharacterControl
        
        '''<summary>
        '''lblDiagnosis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDiagnosis As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtDiagnosis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDiagnosis As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtMemberName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtMemberRank control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberRank As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtMemberProtectedSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberProtectedSSN As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtDAFSC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDAFSC As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlYearsSatisfactoryService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlYearsSatisfactoryService As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtBodyMassIndex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBodyMassIndex As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlMissedWorkDays control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMissedWorkDays As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlSpecialistRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSpecialistRequired As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''rblEROrUrgentCareVisits control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblEROrUrgentCareVisits As Global.System.Web.UI.WebControls.RadioButtonList
        
        '''<summary>
        '''tdERorUrgentCareDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdERorUrgentCareDetails As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''txtERorUrgentCareDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtERorUrgentCareDetails As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rblHospitalizations control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblHospitalizations As Global.System.Web.UI.WebControls.RadioButtonList
        
        '''<summary>
        '''tdHospitalizationsDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdHospitalizationsDetails As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''lblHospitalizationsDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHospitalizationsDetails As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtHospitalizationDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHospitalizationDetails As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlIncapacitationRisk control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIncapacitationRisk As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlFollowUpInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFollowUpInterval As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlDAWGRecommendation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDAWGRecommendation As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''rblDutyInterference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblDutyInterference As Global.System.Web.UI.WebControls.RadioButtonList
        
        '''<summary>
        '''txtPrognosis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrognosis As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtTreatment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTreatment As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtMedicationDosages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMedicationDosages As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.RW.SC_RWMaster
            Get
                Return CType(MyBase.Master,ALOD.Web.Special_Case.RW.SC_RWMaster)
            End Get
        End Property
    End Class
End Namespace
