'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.BMT
    
    Partial Public Class Secure_bmt_CaseDialogue
        
        '''<summary>
        '''UpdatePanel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''CaseDialogue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CaseDialogue As Global.ALOD.Secure.[Shared].UserControls.CaseDialogue
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.BMT.SC_BMTMaster
            Get
                Return CType(MyBase.Master,ALOD.Web.Special_Case.BMT.SC_BMTMaster)
            End Get
        End Property
    End Class
End Namespace
