'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.WWD

    Partial Public Class Secure_sc_WD_MedOff

        '''<summary>
        '''pnlBoardMedicalInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBoardMedicalInformation As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ucICDCodeControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucICDCodeControl As Global.ALOD.Web.UserControls.ICDCodeControl

        '''<summary>
        '''UpdatePanel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ucICD7thCharacterControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucICD7thCharacterControl As Global.ALOD.Web.UserControls.ICD7thCharacterControl

        '''<summary>
        '''DiagnosisLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DiagnosisLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DiagnosisTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DiagnosisTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DecisionY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DecisionY As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''DecisionN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DecisionN As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''DecisionRFA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DecisionRFA As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''DecisionAdminLOD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DecisionAdminLOD As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''DecisionComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DecisionComment As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DQParagraph control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DQParagraph As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ExpirationDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExpirationDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ReturnToDutyDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReturnToDutyDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlAssignmentLimitationCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAssignmentLimitationCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlMemos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMemos As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlSeniorMedialReviewerInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSeniorMedialReviewerInformation As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''upnlSeniorMedicalReviewerFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlSeniorMedicalReviewerFindings As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''rblSeniorMedicalReviewerDecision control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSeniorMedicalReviewerDecision As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''pnlSeniorMedicalReviewerFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSeniorMedicalReviewerFindings As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rblSeniorMedicalReviewerFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSeniorMedicalReviewerFindings As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''txtSeniorMedicalReviewerDecisionComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeniorMedicalReviewerDecisionComment As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''upnlSeniorMedicalReviewerAdditionalData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlSeniorMedicalReviewerAdditionalData As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''pnlSeniorMedicalReviewerAdditionalData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSeniorMedicalReviewerAdditionalData As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UpdatePanel3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ucSeniorMedicalReviewerICDCodeControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucSeniorMedicalReviewerICDCodeControl As Global.ALOD.Web.UserControls.ICDCodeControl

        '''<summary>
        '''UpdatePanel4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ucSeniorMedicalReviewerICD7thCharacterControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucSeniorMedicalReviewerICD7thCharacterControl As Global.ALOD.Web.UserControls.ICD7thCharacterControl

        '''<summary>
        '''lblSeniorMedicalReviewerDiagnosisText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSeniorMedicalReviewerDiagnosisText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSeniorMedicalReviewerDiagnosisText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeniorMedicalReviewerDiagnosisText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSeniorMedicalReviewerDQParagraph control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeniorMedicalReviewerDQParagraph As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSeniorMedicalReviewerExpirationDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeniorMedicalReviewerExpirationDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSeniorMedicalReviewerReturnToDutyDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeniorMedicalReviewerReturnToDutyDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlSeniorMedicalReviewerAssignmentLimitationCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSeniorMedicalReviewerAssignmentLimitationCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''upnlSeniorMedicalReviewerMemos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlSeniorMedicalReviewerMemos As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ddlSeniorMedicalReviewerMemos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSeniorMedicalReviewerMemos As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.WWD.SC_WWDMaster
            Get
                Return CType(MyBase.Master, ALOD.Web.Special_Case.WWD.SC_WWDMaster)
            End Get
        End Property
    End Class
End Namespace
