'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.WWD
    
    Partial Public Class Secure_sc_WD_MedTech
        
        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ddlMedGroups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMedGroups As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''Label5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ddlRMUs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRMUs As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''POCUnitLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents POCUnitLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''POCNameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents POCNameLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''POCPhoneLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents POCPhoneLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''POCEmailLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents POCEmailLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Label17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label17 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''DocumentsAttachedY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DocumentsAttachedY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''DocumentsAttachedN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DocumentsAttachedN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Label7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''CoverLetterY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CoverLetterY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''CoverLetterN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CoverLetterN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''ucICDCodeControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucICDCodeControl As Global.ALOD.Web.UserControls.ICDCodeControl
        
        '''<summary>
        '''UpdatePanel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''ucICD7thCharacterControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucICD7thCharacterControl As Global.ALOD.Web.UserControls.ICD7thCharacterControl
        
        '''<summary>
        '''DiagnosisLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DiagnosisLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''DiagnosisTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DiagnosisTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Documentation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Documentation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Label8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''AFForm469Y control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AFForm469Y As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''AFForm469N control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AFForm469N As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Label20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label20 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtCode37Date control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCode37Date As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label14 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''NarrativeSummaryY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NarrativeSummaryY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''NarrativeSummaryN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NarrativeSummaryN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Label10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''IPEBElectionY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IPEBElectionY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''IPEBElectionN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IPEBElectionN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''IPEBRefusalY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IPEBRefusalY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''IPEBRefusalN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IPEBRefusalN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Label15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label15 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''IPEBSignatureDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IPEBSignatureDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label16 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''MUQRequestDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MUQRequestDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''MUQUploadDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MUQUploadDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''pnlAFRC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAFRC As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''Label11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''MemberStatementY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberStatementY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''MemberStatementN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberStatementN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Label12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''UnitCommanderMemoY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitCommanderMemoY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''UnitCommanderMemoN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitCommanderMemoN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Label13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''MEFSSignatureDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MEFSSignatureDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label18 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''MEFSWaiverDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MEFSWaiverDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label19 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''PrivatePhysicianY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PrivatePhysicianY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''PrivatePhysicianN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PrivatePhysicianN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''MailingRequests control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MailingRequests As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Label25 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label25 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''PS3811RequestDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PS3811RequestDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label26 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label26 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''PS3811SignatureDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PS3811SignatureDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label30 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label30 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''PS3811UploadY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PS3811UploadY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''PS3811UploadN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PS3811UploadN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Label27 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label27 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''FirstClassMailDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FirstClassMailDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label28 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label28 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''MemberContactY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberContactY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''MemberContactN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberContactN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Label29 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label29 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''MemberLetterY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberLetterY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''MemberLetterN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberLetterN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.WWD.SC_WWDMaster
            Get
                Return CType(MyBase.Master,ALOD.Web.Special_Case.WWD.SC_WWDMaster)
            End Get
        End Property
    End Class
End Namespace
