'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.DW

	Partial Public Class Secure_SC_DW_MedTech

		'''<summary>
		'''txtPOCNameLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPOCNameLabel As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''txtPOCPhoneLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPOCPhoneLabel As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''txtPOCEmailLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPOCEmailLabel As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''Label10 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtDeployStart control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtDeployStart As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''Label2 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtDeployEnd control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtDeployEnd As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''Label1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtDeployLocation control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtDeployLocation As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''txtLineNumber control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtLineNumber As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''txtLineRemarks control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtLineRemarks As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''Master property.
		'''</summary>
		'''<remarks>
		'''Auto-generated property.
		'''</remarks>
		Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.DW.SC_DWMaster
			Get
				Return CType(MyBase.Master, ALOD.Web.Special_Case.DW.SC_DWMaster)
			End Get
		End Property
	End Class
End Namespace
