namespace ALOD.Logging
{
    public enum UserAction : byte
    {
        RequestUserRole = 1,
        ModifyAccountStatus = 2,
        ModifyUserGroup = 3,
        ViewPage = 4,
        ModifyGroupPermissions = 5,
        Override = 6,
        ModifyPermission = 7,
        FeedbackResolved = 8,
        RoleChanged = 9,
        EditDocument = 10,
        AddedDocument = 11,
        ViewDocument = 12,
        DocumentDeleted = 13,
        Signed = 14,
        StatusChanged = 15,
        DeletedCase = 16,
        InitiatedLOD = 17,
        ChangedFormData = 18,
        AssignedIO = 19,
        UserLogin = 20,
        ModifyUserPermissions = 21,
        CreatedUserRole = 22,
        ApprovedRoleChange = 23,
        DeniedRoleChange = 24,
        ModifyUserRole = 25,
        DeletedUserRole = 26,
        CreatedNewAccount = 27,
        CreateNewUnit = 28,
        ModifyUnit = 29,
        CommentDelete = 30,
        MessageAdd = 31,
        MessageModify = 32,
        MessageDelete = 33,
        ModifyMemberData = 34,
        RequestedReinvestigation = 35,
        InitiatedSpecialCase = 36,
        PostCompletion = 37,
        KeyValEdited = 38,
        KeyValAdded = 39,
        KeyValDeleted = 40,
        AutoDisable = 41,
        RequestedAppeal = 42,
        InitiatedSARC = 43,
        UpdateCaseUnit = 44,
        MemoAdded = 45
    }
}