'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.PSCD

    Partial Public Class Secure_PSCD_PSCDBoard

        '''<summary>
        '''pnlBoardFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBoardFindings As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ucHQMedTechFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucHQMedTechFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''ucBoardMedicalFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucBoardMedicalFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''ucSeniorMedicalFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucSeniorMedicalFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''ucBoardLegalFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucBoardLegalFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''ucPersonnelFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucPersonnelFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''upnlPersonnelFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlPersonnelFindings_v2 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''bdPersonnel_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdPersonnel_v2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''Label1_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''bdPersonnellbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdPersonnellbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''BPR_DESCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BPR_DESCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''bdPersonnelChecklbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdPersonnelChecklbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ucApprovingAuthorityFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucApprovingAuthorityFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''bdfrmlPersonnel_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdfrmlPersonnel_v2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''FRMLPersonnel_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FRMLPersonnel_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''AAR_DESCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AAR_DESCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''bdFrmlPersonnelChecklbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdFrmlPersonnelChecklbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.PSCD.SC_PSCDMaster
            Get
                Return CType(MyBase.Master, ALOD.Web.Special_Case.PSCD.SC_PSCDMaster)
            End Get
        End Property
    End Class
End Namespace
