'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.LOD

    Partial Public Class Secure_lod_lodBoard

        '''<summary>
        '''LOD_Original control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LOD_Original As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dvFormal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvFormal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''FrmlAppointingAuthority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlAppointingAuthority As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fcfrmlAppAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fcfrmlAppAuth As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckAppointing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckAppointing As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''dvspfrmlAppAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvspfrmlAppAuth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''FrmlBoardLegal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlBoardLegal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdfrmlLegalFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdfrmlLegalFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckLegalFormal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckLegalFormal As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''dvsp5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''FrmlBoardMedical control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlBoardMedical As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdfrmlMedicalFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdfrmlMedicalFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckMedicalFormal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckMedicalFormal As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''dvsp7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''FrmlBoardPersonnel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlBoardPersonnel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFrmlCredibleService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFrmlCredibleService As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rblFrmlCredibleService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblFrmlCredibleService As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''lblFrmlWasMemberOnOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFrmlWasMemberOnOrders As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rblFrmlWasMemberOnOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblFrmlWasMemberOnOrders As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''bdfrmlPersonnelFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdfrmlPersonnelFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckPersonnelFormal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckPersonnelFormal As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''dvsp6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''FrmlBoardAAReview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlBoardAAReview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdFrmlAppAuthFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdFrmlAppAuthFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckAAFormal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckAAFormal As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''dvsp8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''FromalBoardRA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FromalBoardRA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdFormalRAFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdFormalRAFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''lblSelectedFormalApprovingAuthority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectedFormalApprovingAuthority As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlFormalApprovingAuthorities control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFormalApprovingAuthorities As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dvsp9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''dvInformal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvInformal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''AppointingAuthority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AppointingAuthority As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fcAppAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fcAppAuth As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''Div2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''BoardLegal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BoardLegal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdLegalFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdLegalFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckLegal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckLegal As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''dvsp1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''BoardMedical control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BoardMedical As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdMedicalFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdMedicalFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckMedical control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckMedical As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''dvsp3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''BoardPersonnel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BoardPersonnel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblCredibleService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCredibleService As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rblCredibleService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblCredibleService As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''lblWasMemberOnOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWasMemberOnOrders As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rblWasMemberOnOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblWasMemberOnOrders As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''bdPersonnelFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdPersonnelFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckPersonnel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckPersonnel As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''dvsp2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''BoardAAReview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BoardAAReview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdAppAuthFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdAppAuthFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckAA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckAA As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''dvsp4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''AFRCBoard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AFRCBoard As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckBoardTech control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckBoardTech As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''lblSelectedApprovingAuthority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectedApprovingAuthority As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlApprovingAuthorities control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlApprovingAuthorities As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dvsp04 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp04 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LOD_v2_panel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LOD_v2_panel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dvFormal_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvFormal_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''FrmlAppointingAuthority_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlAppointingAuthority_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fcfrmlAppAuth_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fcfrmlAppAuth_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckAppointing_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckAppointing_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''FrmlBoardLegal_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlBoardLegal_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdfrmlLegalFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdfrmlLegalFindings_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckLegalFormal_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckLegalFormal_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''FrmlBoardMedical_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlBoardMedical_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdfrmlMedicalFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdfrmlMedicalFindings_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckMedicalFormal_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckMedicalFormal_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''FrmlBoardPersonnel_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlBoardPersonnel_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''upnlFormalPersonnelFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlFormalPersonnelFindings_v2 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''bdfrmlPersonnelFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdfrmlPersonnelFindings_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''bdfrmlPersonnel_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdfrmlPersonnel_v2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''FRMLPersonnel_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FRMLPersonnel_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''bdFRMLPersonnellbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdFRMLPersonnellbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''bdfrmlPersonnelREFER_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdfrmlPersonnelREFER_v2 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''bdFrmlPersonnelChecklbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdFrmlPersonnelChecklbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SigCheckPersonnelFormal_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckPersonnelFormal_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''FrmlBoardAAReview_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlBoardAAReview_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''upnlFormalAppAuthFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlFormalAppAuthFindings_v2 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''bdFrmlAppAuthFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdFrmlAppAuthFindings_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''bdfrmlAppAuth_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdfrmlAppAuth_v2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''FrmlAppAuth_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlAppAuth_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FrmlAppAuthlbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlAppAuthlbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FrmlAppAuthREFER_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlAppAuthREFER_v2 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''FrmlAppAuthChecklbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FrmlAppAuthChecklbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SigCheckAAFormal_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckAAFormal_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''FromalBoardRA_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FromalBoardRA_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdFormalRAFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdFormalRAFindings_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''lblSelectedFormalApprovingAuthority_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectedFormalApprovingAuthority_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlFormalApprovingAuthorities_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFormalApprovingAuthorities_v2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dvInformal_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvInformal_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''AppointingAuthority_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AppointingAuthority_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fcAppAuth_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fcAppAuth_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''BoardMedical_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BoardMedical_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdMedicalFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdMedicalFindings_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckMedical_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckMedical_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''BoardLegal_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BoardLegal_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdLegalFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdLegalFindings_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''SigCheckLegal_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckLegal_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''BoardPersonnel_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BoardPersonnel_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''upnlPersonnelFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlPersonnelFindings_v2 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''bdPersonnelFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdPersonnelFindings_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''bdPersonnel_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdPersonnel_v2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''Label1_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''bdPersonnellbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdPersonnellbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''bdPersonnelREFER_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdPersonnelREFER_v2 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''bdPersonnelChecklbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdPersonnelChecklbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SigCheckPersonnel_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckPersonnel_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''BoardAAReview_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BoardAAReview_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''upnlAppAuthFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlAppAuthFindings_v2 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''bdAppAuthFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdAppAuthFindings_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''bdAppAuth_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdAppAuth_v2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''Label2_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''bdAppAuthlbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdAppAuthlbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''bdAppAuthREFER_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdAppAuthREFER_v2 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''bdAppAuthChecklbl_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdAppAuthChecklbl_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SigCheckAA_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckAA_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''AFRCBoard_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AFRCBoard_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''bdFindings_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bdFindings_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl

        '''<summary>
        '''lblSelectedApprovingAuthority_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectedApprovingAuthority_v2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlApprovingAuthorities_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlApprovingAuthorities_v2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SigCheckBoardTech_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigCheckBoardTech_v2 As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''dvsp04_v2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvsp04_v2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.LOD.LodMaster
            Get
                Return CType(MyBase.Master, ALOD.Web.LOD.LodMaster)
            End Get
        End Property
    End Class
End Namespace
