'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.LOD
    
    Partial Public Class SeniorMedReviewer
        
        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''SeniorMedical control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SeniorMedical As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''FindingsTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FindingsTitle As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ucSeniorMedicalFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucSeniorMedicalFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl
        
        '''<summary>
        '''ucSigCheckSeniorMedical control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucSigCheckSeniorMedical As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.LOD.LodMaster
            Get
                Return CType(MyBase.Master,ALOD.Web.LOD.LodMaster)
            End Get
        End Property
    End Class
End Namespace
