'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.CI
    
    Partial Public Class Secure_sc_ci_HQTech
        
        '''<summary>
        '''lblTMTNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTMTNumber As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblAFRC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAFRC As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''TMTNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMTNumber As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblTMTRecDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTMTRecDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''TMTRecDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMTRecDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblSuspenseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSuspenseDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''SuspenseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SuspenseDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''hdnInitialHash control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnInitialHash As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hdnOldControlList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnOldControlList As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''page_refid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents page_refid As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''page_readOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents page_readOnly As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.CI.SC_CongressMaster
            Get
                Return CType(MyBase.Master,ALOD.Web.Special_Case.CI.SC_CongressMaster)
            End Get
        End Property
    End Class
End Namespace
