'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.MEB

    Partial Public Class Secure_sc_meb_MedOff

        '''<summary>
        '''pnlBoardMedicalInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBoardMedicalInformation As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UpdatePanel5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''rblDecision control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblDecision As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''lblDecisionExplanation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDecisionExplanation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtDecisionComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDecisionComment As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ucICDCodeControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucICDCodeControl As Global.ALOD.Web.UserControls.ICDCodeControl

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ucICD7thCharacterControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucICD7thCharacterControl As Global.ALOD.Web.UserControls.ICD7thCharacterControl

        '''<summary>
        '''Label55 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label55 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DiagnosisLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DiagnosisLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtDiagnosis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDiagnosis As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rblDetermination control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblDetermination As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''Label5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlAssignmentLimitation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAssignmentLimitation As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlMemos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMemos As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ObjectDataSource1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjectDataSource1 As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''pnlSeniorMedialReviewerInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSeniorMedialReviewerInformation As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''upnlSeniorMedicalReviewerFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlSeniorMedicalReviewerFindings As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''rblSeniorMedicalReviewerConcur control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSeniorMedicalReviewerConcur As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''pnlSeniorMedicalReviewerFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSeniorMedicalReviewerFindings As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rblSeniorMedicalReviewerFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSeniorMedicalReviewerFindings As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''txtSeniorMedicalReviewerDecisionComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeniorMedicalReviewerDecisionComment As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''upnlSeniorMedicalReviewerAdditionalData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlSeniorMedicalReviewerAdditionalData As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''pnlSeniorMedicalReviewerAdditionalData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSeniorMedicalReviewerAdditionalData As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rblSeniorMedicalReviewerDecision control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSeniorMedicalReviewerDecision As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanel3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ucSeniorMedicalReviewerICDCodeControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucSeniorMedicalReviewerICDCodeControl As Global.ALOD.Web.UserControls.ICDCodeControl

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanel4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ucSeniorMedicalReviewerICD7thCharacterControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucSeniorMedicalReviewerICD7thCharacterControl As Global.ALOD.Web.UserControls.ICD7thCharacterControl

        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSeniorMedicalReviewerDiagnosis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeniorMedicalReviewerDiagnosis As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlSeniorMedicalReviewerAssignmentLimitation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSeniorMedicalReviewerAssignmentLimitation As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlSeniorMedicalReviewerMemos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSeniorMedicalReviewerMemos As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ObjectDataSource2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjectDataSource2 As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.MEB.SC_MEBMaster
            Get
                Return CType(MyBase.Master, ALOD.Web.Special_Case.MEB.SC_MEBMaster)
            End Get
        End Property
    End Class
End Namespace
