'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Controls.Document

    Partial Public Class Controls_Document

        '''<summary>
        '''ScriptManagerProxy1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManagerProxy1 As Global.System.Web.UI.ScriptManagerProxy

        '''<summary>
        '''menu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents menu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''menuDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents menuDelete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''divThumbnails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divThumbnails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''divContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
