'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.UserControls
    
    Partial Public Class Secure_Shared_UserControls_CaseTracking
        
        '''<summary>
        '''Content2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Content2 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''chkShowAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowAll As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''imgPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPrint As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''TrackingList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TrackingList As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''Content3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Content3 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''smp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents smp As Global.System.Web.UI.ScriptManagerProxy
    End Class
End Namespace
