'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.UserControls

    Partial Public Class Secure_Shared_UserControls_CaseHistory

        '''<summary>
        '''HistoryPanelLOD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryPanelLOD As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''HistoryGridLOD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryGridLOD As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''NoHistoryLODLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NoHistoryLODLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HistoryPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''HistoryGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''NoHistoryLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NoHistoryLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HistoryPanelPAL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryPanelPAL As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''HistoryGridPAL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryGridPAL As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''NoHistoryPALLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NoHistoryPALLbl As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
