'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.UserControls

    Partial Public Class Secure_Shared_UserControls_ReportNav

        '''<summary>
        '''InputPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InputPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''upnlMemberLookup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlMemberLookup As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''tbl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbl1 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''tr1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ReportLabel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportLabel1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlUnit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUnit As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tr2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tr2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ReportLabel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportLabel2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkSubordinateUnit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSubordinateUnit As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''tr3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tr3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ReportLabel3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportLabel3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBeginDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBeginDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tr4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tr4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ReportLabel4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportLabel4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trRadioButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trRadioButtons As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblMemberNameRadioButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMemberNameRadioButtons As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rdbSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbSSN As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rdbName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbName As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''tr5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tr5 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ReportLabel5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportLabel5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSSN As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblReportMemberName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportMemberName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMemberLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMemberFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMemberMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberMiddleName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMemberNotFound control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMemberNotFound As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvalidMemberName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvalidMemberName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tr6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tr6 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ReportLabel6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportLabel6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rblLodStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblLodStatus As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''tr7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tr7 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ReportLabel7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportLabel7 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SortOrdeDDL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SortOrdeDDL As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tr8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tr8 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''CompoLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompoLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CompoSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompoSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tbl2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbl2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''ReportLabel8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportLabel8 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ReportButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''errorLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents errorLbl As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
