'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.UserControls

    Partial Public Class Secure_Shared_UserControls_SigntureCheck

        '''<summary>
        '''proxy1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents proxy1 As Global.System.Web.UI.ScriptManagerProxy

        '''<summary>
        '''WrapperPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WrapperPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''StatusImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''StatusLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusLabel As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
