'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.PH
    
    Partial Public Class History
        
        '''<summary>
        '''pnlWingPHHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlWingPHHistory As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblHistoryPanelTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHistoryPanelTitle As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''gdvPHHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvPHHistory As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''lblNoHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoHistory As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.PH.SC_PHMaster
            Get
                Return CType(MyBase.Master,ALOD.Web.Special_Case.PH.SC_PHMaster)
            End Get
        End Property
    End Class
End Namespace
