'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Admin

    Partial Public Class Secure_Shared_Admin_EditUser

        '''<summary>
        '''smp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents smp As Global.System.Web.UI.ScriptManagerProxy

        '''<summary>
        '''RoleDialogValues control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RoleDialogValues As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RoleDialogButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RoleDialogButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''RoleUpdateButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RoleUpdateButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''unitSearcher control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents unitSearcher As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_unitSearcher

        '''<summary>
        '''hdnIdClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnIdClient As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hdnNameClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnNameClient As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lnkManageUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkManageUsers As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ReturnImage1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReturnImage1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lnkManageMembers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkManageMembers As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ReturnImage2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReturnImage2 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lnkManageRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkManageRoles As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ReturnImage3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReturnImage3 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lnkPermissionReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkPermissionReport As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ReturnImage4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReturnImage4 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''PendingPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PendingPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''DisabledPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DisabledPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UsernameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UsernameLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CompoSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompoSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''NameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SsnLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SsnLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''RankLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RankLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''StatusLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ActionLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ActionLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''EnableButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnableButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''DisableButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DisableButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''AdminDisabledLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AdminDisabledLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ConfirmButtonExtender1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConfirmButtonExtender1 As Global.AjaxControlToolkit.ConfirmButtonExtender

        '''<summary>
        '''ConfirmButtonExtender2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConfirmButtonExtender2 As Global.AjaxControlToolkit.ConfirmButtonExtender

        '''<summary>
        '''MultipleAccountsPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MultipleAccountsPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''AccountsGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AccountsGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''CreateAccountButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CreateAccountButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''RolesGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RolesGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''PendingGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PendingGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''CompletedGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompletedGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ChangeRoleSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChangeRoleSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''RequestRoleButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequestRoleButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ControlsPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ControlsPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''vld_Summary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vld_Summary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''RankSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RankSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ViewSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ViewSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ViewSelectLODPm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ViewSelectLODPm As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''EDIPINtxt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EDIPINtxt As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidator3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator3 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''UnitTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ChangeUnitButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChangeUnitButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''RequiredFieldValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''newUnitIDLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents newUnitIDLabel As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''adUnitTextBoX control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents adUnitTextBoX As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ChangeAdUnitBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChangeAdUnitBtn As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''adUnitIDLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents adUnitIDLabel As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''ExpirationBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExpirationBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ReceiveEmailCheck control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReceiveEmailCheck As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ReceiveReminderEmailCheck control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReceiveReminderEmailCheck As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CommentsBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CommentsBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PhoneBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PhoneBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqfd_Comm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqfd_Comm As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rgExpCom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgExpCom As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''DsnBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DsnBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rgExpDSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgExpDSN As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''FilteredTextBoxExtender1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FilteredTextBoxExtender1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''EmailBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EmailBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqfd_Email control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqfd_Email As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rgExp_Email control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgExp_Email As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''Email2Box control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Email2Box As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''Email3Box control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Email3Box As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidator2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator2 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''StreetBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StreetBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RequiredFieldValidator2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''CityBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CityBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RequiredFieldValidator3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''StateSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StateSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''RequiredFieldValidator4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''ZipBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ZipBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''regExp_Zip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents regExp_Zip As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''RequiredFieldValidator5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''updateButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents updateButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''hdButtonClicked control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdButtonClicked As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''PrintHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PrintHistory As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''HistoryGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''hdnInitialHash control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnInitialHash As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hdnOldControlList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnOldControlList As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
