'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Admin

    Partial Public Class Secure_Shared_Admin_MemoMappedValues

        '''<summary>
        '''lblKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblKey As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlMemoKeys control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMemoKeys As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''gvValues control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvValues As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''memoValues control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents memoValues As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''memoKeys control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents memoKeys As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
