'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.MO

    Partial Public Class Secure_mo_MyCases

        '''<summary>
        '''resultsUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents resultsUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''imgWait control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgWait As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''gvResults11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvResults11 As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''gvDisposition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvDisposition As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''gvHolding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvHolding As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''SCData_Module11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SCData_Module11 As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''SCDisposition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SCDisposition As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''SCDisposition2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SCDisposition2 As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''resultsUpdatePanelAnimationExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents resultsUpdatePanelAnimationExtender As Global.AjaxControlToolkit.UpdatePanelAnimationExtender
    End Class
End Namespace
