'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.MMSO
    
    Partial Public Class Secure_sc_mmso_Documents
        
        '''<summary>
        '''DocumentTypeSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DocumentTypeSelect As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''DocumentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DocumentDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''DocumentDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DocumentDescription As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''UpdateDocumentButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdateDocumentButton As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''DocumentEditValues control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DocumentEditValues As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''TemplateSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TemplateSelect As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''RefreshButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RefreshButton As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''CategoryRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CategoryRepeater As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
