'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.LOD

    Partial Public Class Secure_lod_Inbox

        '''<summary>
        '''ErrorPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''ErrorMessageLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorMessageLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''StartPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StartPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UsernameInput control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UsernameInput As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SearchButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UserPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UserSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''FormalSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormalSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SarcCheck control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SarcCheck As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ViewInboxButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ViewInboxButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ResetButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ResetButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UserDataLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserDataLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ResultGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ResultGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''LodData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LodData As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
