'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.LOD
    
    Partial Public Class Secure_lod_Start
        
        '''<summary>
        '''InputPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InputPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''upnlMemberLookup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlMemberLookup As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''trRadioButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trRadioButtons As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''rdbSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbSSN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''rdbName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbName As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''trSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSSN As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''SSNTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SSNTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''NotFoundLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NotFoundLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''InvalidSSNLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InvalidSSNLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblInvalidMemberForSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvalidMemberForSSN As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''trSSN2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSSN2 As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''SSNTextBox2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SSNTextBox2 As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''InvalidLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InvalidLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''InvalidSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InvalidSSN As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''trName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trName As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''txtMemberLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberLastName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtMemberFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberFirstName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtMemberMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMemberMiddleName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblMemberNotFound control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMemberNotFound As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblInvalidMemberName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvalidMemberName As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblInvalidMemberForName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvalidMemberForName As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''LookupButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LookupButton As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''MemberSelectionPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberSelectionPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''ucMemberSelectionGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucMemberSelectionGrid As Global.ALOD.Web.UserControls.MemberSearchResultsGrid
        
        '''<summary>
        '''MemberDataPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MemberDataPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''SSNLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SSNLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ChangeSsnButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChangeSsnButton As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''CompoLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompoLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''NameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''DoBLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DoBLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''GradeCodeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GradeCodeLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''RankLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RankLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''UnitNameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitNameLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''UnitCodeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitCodeLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''UnitIdLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitIdLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''WorkflowSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkflowSelect As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''TmnPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TmnPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''TmnYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TmnYes As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''TmnNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TmnNo As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''lblTMN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTMN As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''TmsPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TmsPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''TmsYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TmsYes As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''TmsNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TmsNo As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''lblTMS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTMS As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''SarcPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SarcPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''SarcYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SarcYes As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''SarcNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SarcNo As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''lblSARC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSARC As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''RestrictedPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RestrictedPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''RestrictedYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RestrictedYes As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''RestrictedNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RestrictedNo As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''lblRestricted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRestricted As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''CreateButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CreateButton As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''SigBlock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SigBlock As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SignatureBlock
        
        '''<summary>
        '''ErrorRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorRow As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''ErrorLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ErrorPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''ValidationList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationList As Global.System.Web.UI.WebControls.BulletedList
        
        '''<summary>
        '''HistoryPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''HistoryGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryGrid As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''WorkflowData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkflowData As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''AttachedUnitNameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AttachedUnitNameLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''AttachedUnitCodeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AttachedUnitCodeLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''AttachedUnitIdLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AttachedUnitIdLabel As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
