'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.IRILO
    
    Partial Public Class Secure_sc_FastTrack_HQTech
        
        '''<summary>
        '''lblHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''DecisionY control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DecisionY As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''DecisionN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DecisionN As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''DecisionComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DecisionComment As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.IRILO.SC_FastTrackMaster
            Get
                Return CType(MyBase.Master,ALOD.Web.Special_Case.IRILO.SC_FastTrackMaster)
            End Get
        End Property
    End Class
End Namespace
