'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.IRILO

    Partial Public Class Secure_FastTrack_init

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.IRILO.SC_FastTrackMaster
            Get
                Return CType(MyBase.Master, ALOD.Web.Special_Case.IRILO.SC_FastTrackMaster)
            End Get
        End Property
    End Class
End Namespace
