'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.IRILO
    
    Partial Public Class Secure_sc__ft_lod_Documents
        
        '''<summary>
        '''accLODDocuments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents accLODDocuments As Global.AjaxControlToolkit.Accordion
        
        '''<summary>
        '''pnlNoLODs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNoLODs As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblNoLODsMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoLODsMessage As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
