'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.PW

	Partial Public Class Secure_sc_pw_MedTech

		'''<summary>
		'''PWCategoryDropdownListSelect control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents PWCategoryDropdownListSelect As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''txtPOCNameLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPOCNameLabel As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''txtPOCPhoneLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPOCPhoneLabel As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''txtPOCEmailLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPOCEmailLabel As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''UpdatePanel1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

		'''<summary>
		'''ucICDCodeControl control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ucICDCodeControl As Global.ALOD.Web.UserControls.ICDCodeControl

		'''<summary>
		'''UpdatePanel2 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

		'''<summary>
		'''ucICD7thCharacterControl control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ucICD7thCharacterControl As Global.ALOD.Web.UserControls.ICD7thCharacterControl

		'''<summary>
		'''DiagnosisLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents DiagnosisLabel As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''DiagnosisTextBox control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents DiagnosisTextBox As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''PWCategoriesObjectDataSource control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents PWCategoriesObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

		'''<summary>
		'''Master property.
		'''</summary>
		'''<remarks>
		'''Auto-generated property.
		'''</remarks>
		Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.PW.SC_PWaiverMaster
			Get
				Return CType(MyBase.Master, ALOD.Web.Special_Case.PW.SC_PWaiverMaster)
			End Get
		End Property
	End Class
End Namespace
