'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.RR
    
    Partial Public Class Secure_rr_WingJA
        
        '''<summary>
        '''ucWingJAFindings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucWingJAFindings As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_FindingsControl
        
        '''<summary>
        '''ucSigCheckWingJA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucSigCheckWingJA As Global.ALOD.Web.UserControls.Secure_Shared_UserControls_SigntureCheck
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ALOD.Web.RR.ReinvestigationRequestMaster
            Get
                Return CType(MyBase.Master,ALOD.Web.RR.ReinvestigationRequestMaster)
            End Get
        End Property
    End Class
End Namespace
