//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALOD.Web
{
    public partial class Public_Register3
    {
        /// <summary>
        /// lblInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblInfo;

        /// <summary>
        /// Displaypanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel Displaypanel;

        /// <summary>
        /// FullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label FullName;

        /// <summary>
        /// RankDisplay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label RankDisplay;

        /// <summary>
        /// UnitLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label UnitLabel;

        /// <summary>
        /// UserRoleLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label UserRoleLabel;

        /// <summary>
        /// EmailLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label EmailLabel;

        /// <summary>
        /// Email2Label control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Email2Label;

        /// <summary>
        /// Email3Label control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Email3Label;

        /// <summary>
        /// PhoneLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label PhoneLabel;

        /// <summary>
        /// DsnLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label DsnLabel;

        /// <summary>
        /// AddressLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label AddressLabel;

        /// <summary>
        /// CityLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label CityLabel;

        /// <summary>
        /// StateLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label StateLabel;

        /// <summary>
        /// ZipLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ZipLabel;

        /// <summary>
        /// RecieveEmailLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label RecieveEmailLabel;

        /// <summary>
        /// PrevButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button PrevButton;

        /// <summary>
        /// NextButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button NextButton;
    }
}
