//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALOD.Web
{
    public partial class login_SelectAccount
    {
        /// <summary>
        /// AccountRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater AccountRepeater;
    }
}
