'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Sys

    Partial Public Class EditUnit

        '''<summary>
        '''pnlUnitDuty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUnitDuty As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gdvUnitDuty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvUnitDuty As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblAddDuty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAddDuty As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAddDuty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddDuty As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSortOrderDuty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSortOrderDuty As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSortOrderDuty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSortOrderDuty As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTypeDuty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTypeDuty As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTypeDuty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTypeDuty As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnAddDuty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddDuty As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlUnitSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUnitSource As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gdvUnitSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvUnitSource As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblAddSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAddSource As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAddSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddSource As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSortOrderSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSortOrderSource As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSortOrderSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSortOrderSource As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnAddSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddSource As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlUnitOccurrence control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUnitOccurrence As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gdvUnitOccurrence control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvUnitOccurrence As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblAddOccurrence control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAddOccurrence As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAddOccurrence control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddOccurrence As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSortOrderOccurrence control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSortOrderOccurrence As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSortOrderOccurrence control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSortOrderOccurrence As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnAddOccurrence control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddOccurrence As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlUnitProximate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUnitProximate As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gdvUnitProximate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvUnitProximate As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblAddProximate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAddProximate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAddProximate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddProximate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSortOrderProximate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSortOrderProximate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSortOrderProximate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSortOrderProximate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnAddProximate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddProximate As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
