'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Sys

    Partial Public Class EditCertificationStamps

        '''<summary>
        '''btnAddCertificationStamp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddCertificationStamp As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''gdvCertificationStamps control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvCertificationStamps As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''pnlWorkflowMaps control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlWorkflowMaps As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gdvCertificationStampWorkflows control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvCertificationStampWorkflows As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''btnUpdateWorkflowMappings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateWorkflowMappings As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancelWorkflowMappings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelWorkflowMappings As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlEditCertificationStamp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEditCertificationStamp As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblEditBlockLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEditBlockLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtStampName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStampName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtStampBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStampBody As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkStampIsQualified control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStampIsQualified As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''btnInsertCertificationStamp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnInsertCertificationStamp As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUpdateCertificationStamp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateCertificationStamp As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancelCertificationStamp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelCertificationStamp As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''trValidationErrors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trValidationErrors As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''bllValidationErrors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bllValidationErrors As Global.System.Web.UI.WebControls.BulletedList
    End Class
End Namespace
