'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Sys

    Partial Public Class EditCompletedByGroups

        '''<summary>
        '''gdvCompletedByGroups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvCompletedByGroups As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblAddCompletedByGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAddCompletedByGroup As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAddCompletedByGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddCompletedByGroup As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnAddCompletedByGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddCompletedByGroup As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlWorkflowMaps control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlWorkflowMaps As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gdvCompletedByGroupWorkflows control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvCompletedByGroupWorkflows As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''btnUpdateWorkflowMappings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateWorkflowMappings As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancelWorkflowMappings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelWorkflowMappings As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
