'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Sys

    Partial Public Class Secure_Shared_System_ManagePermissions

        '''<summary>
        '''GroupSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GroupSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''PermissionGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PermissionGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''btnUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''dataPerms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dataPerms As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
