'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Sys

    Partial Public Class SystemEmails

        '''<summary>
        '''chkWorkEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkWorkEmail As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkPersonalEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPersonalEmail As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkUnitEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUnitEmail As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlUserGroups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUserGroups As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''chklUserGroups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chklUserGroups As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''btnExportToExcel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExportToExcel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ddlEmailTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEmailTemplates As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSubject As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''txtSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqfdSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqfdSubject As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''pnlBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBody As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''txtBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBody As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqfdBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqfdBody As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''btnSend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSend As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResults As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
