'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Sys
    
    Partial Public Class TestAppWarmupProcesses
        
        '''<summary>
        '''pnlInput control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInput As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''upnlInput control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlInput As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''tblInput control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblInput As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''ddlTypeOfProcess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTypeOfProcess As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''tblInput2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblInput2 As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''txtTestExecutionDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTestExecutionDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnExecuteTest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExecuteTest As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''lblDisabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisabled As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''upnlProcessInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlProcessInfo As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''tblPHProcessInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPHProcessInfo As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''tblReportProcessInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblReportProcessInfo As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''pnlAppWarmupProcessLog control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAppWarmupProcessLog As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''gdvProcessLogs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvProcessLogs As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
