'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.Special_Case.RS

	Partial Public Class Secure_sc_rs_HQTech

		'''<summary>
		'''txtPOCNameLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPOCNameLabel As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''txtPOCPhoneLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPOCPhoneLabel As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''txtPOCEmailLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPOCEmailLabel As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''pnlCaseInfo control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlCaseInfo As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''trCaseType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents trCaseType As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblCaseType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblCaseType As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblOtherCaseTypeName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblOtherCaseTypeName As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''trSubCaseType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents trSubCaseType As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblSubCaseType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblSubCaseType As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblOtherSubCaseTypeName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblOtherSubCaseTypeName As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''upnlCaseInfo control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents upnlCaseInfo As Global.System.Web.UI.UpdatePanel

		'''<summary>
		'''pnlCaseInfoReassessment control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlCaseInfoReassessment As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''utrCaseType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents utrCaseType As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''ddlCaseType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlCaseType As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''utrOtherCaseType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents utrOtherCaseType As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''txtOtherCaseTypeName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtOtherCaseTypeName As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''utrSubCaseType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents utrSubCaseType As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''ddlSubCaseType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlSubCaseType As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''utrOtherSubCaseType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents utrOtherSubCaseType As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''txtOtherSubCaseTypeName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtOtherSubCaseTypeName As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''upnlCaseData control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents upnlCaseData As Global.System.Web.UI.UpdatePanel

		'''<summary>
		'''ddlType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlType As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''OtherTypeRow control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents OtherTypeRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''txtEnterType control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtEnterType As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''ddlRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlRating As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''OtherRatingRow control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents OtherRatingRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''txtEnterRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtEnterRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''ddlDisposition control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlDisposition As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''ddlCompletedByUnit control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlCompletedByUnit As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''OtherCompletedByUnitRow control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents OtherCompletedByUnitRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''txtCompletedByUnitName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtCompletedByUnitName As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''txtDateReceived control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtDateReceived As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''ddlALC control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlALC As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''lblCertificationStamp control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblCertificationStamp As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''ddlCertificationStamp control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlCertificationStamp As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''txtFreeText control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtFreeText As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''trSecondaryCertificationStamp control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents trSecondaryCertificationStamp As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''ddlSecondaryCertificationStamp control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlSecondaryCertificationStamp As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''trSecondaryFreeText control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents trSecondaryFreeText As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''txtSecondaryFreeText control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSecondaryFreeText As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''MemoTemplateRow control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents MemoTemplateRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblMemoTemplateRow control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblMemoTemplateRow As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''ddlMemoTemplates control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlMemoTemplates As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''UpdatePanel4 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

		'''<summary>
		'''lblICDRowText control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblICDRowText As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''ucICDCodeControl control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ucICDCodeControl As Global.ALOD.Web.UserControls.ICDCodeControl

		'''<summary>
		'''ucICD7thCharacterControl control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ucICD7thCharacterControl As Global.ALOD.Web.UserControls.ICD7thCharacterControl

		'''<summary>
		'''lblDiagnosisRowText control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblDiagnosisRowText As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''DiagnosisLabel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents DiagnosisLabel As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''DiagnosisTextBox control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents DiagnosisTextBox As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''Master property.
		'''</summary>
		'''<remarks>
		'''Auto-generated property.
		'''</remarks>
		Public Shadows ReadOnly Property Master() As ALOD.Web.Special_Case.RS.SC_RSMaster
			Get
				Return CType(MyBase.Master, ALOD.Web.Special_Case.RS.SC_RSMaster)
			End Get
		End Property
	End Class
End Namespace
