'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.AP

    Partial Public Class Secure_ap_PostCompletionAppeal

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SsnBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SsnBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''NameBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CaseIdbox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CaseIdbox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''FormalSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormalSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''UnitSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''CheckBoxSearchAllCases control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBoxSearchAllCases As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''SearchButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''resultsUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents resultsUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''NoFiltersPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NoFiltersPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''gvResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvResults As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''AppealData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AppealData As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''resultsUpdatePanelAnimationExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents resultsUpdatePanelAnimationExtender As Global.AjaxControlToolkit.UpdatePanelAnimationExtender
    End Class
End Namespace
