'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web

    Partial Public Class Public_RegisterLink

        '''<summary>
        '''rcphaRadio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcphaRadio As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''rcphaLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcphaLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''IncorrectSSNLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IncorrectSSNLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''InvalidSSNLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InvalidSSNLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''vld_Summary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vld_Summary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''SSNNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SSNNum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SSNTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SSNTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqfd_ssn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqfd_ssn As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''regExpssn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents regExpssn As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''UserNameNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserNameNum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserNameTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserNameTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqfd_un control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqfd_un As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''FirstNameNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FirstNameNum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FirstNameTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FirstNameTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqfd_fn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqfd_fn As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''LastNameNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LastNameNum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LastNameTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LastNameTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqfd_ln control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqfd_ln As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Actionnum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Actionnum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''linkBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkBtn As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''accountLinkedDiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents accountLinkedDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''accountLinkButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents accountLinkButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''registerLinkedDiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents registerLinkedDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''registerLinkButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents registerLinkButton As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
