'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web.SARC
    
    Partial Public Class Secure_sarc_MyCases
        
        '''<summary>
        '''resultsUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents resultsUpdatePanel As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''imgWait control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgWait As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''gvResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvResults As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''sarc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sarc As Global.System.Web.UI.WebControls.SqlDataSource
        
        '''<summary>
        '''SARCData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SARCData As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''resultsUpdatePanelAnimationExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents resultsUpdatePanelAnimationExtender As Global.AjaxControlToolkit.UpdatePanelAnimationExtender
    End Class
End Namespace
