//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALOD.Web.LOD
{
    public partial class Secure_lod_Inbox
    {
        /// <summary>
        /// ErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;

        /// <summary>
        /// Image1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image Image1;

        /// <summary>
        /// ErrorMessageLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ErrorMessageLabel;

        /// <summary>
        /// StartPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel StartPanel;

        /// <summary>
        /// UsernameInput control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox UsernameInput;

        /// <summary>
        /// SearchButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button SearchButton;

        /// <summary>
        /// UserPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel UserPanel;

        /// <summary>
        /// UserSelect control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList UserSelect;

        /// <summary>
        /// FormalSelect control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList FormalSelect;

        /// <summary>
        /// SarcCheck control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox SarcCheck;

        /// <summary>
        /// ViewInboxButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ViewInboxButton;

        /// <summary>
        /// ResetButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ResetButton;

        /// <summary>
        /// UserDataLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label UserDataLabel;

        /// <summary>
        /// ResultGrid control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView ResultGrid;

        /// <summary>
        /// LodData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ObjectDataSource LodData;
    }
}
